# Generated by Django 6.0.5 on 2026-05-13 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('mecanica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quilometragem', models.IntegerField(default=0)),
                ('nivel_combustivel', models.CharField(choices=[('vazio', 'Vazio'), ('1/4', '1/4'), ('1/2', '1/2'), ('3/4', '3/4'), ('cheio', 'Cheio')], default='1/2', max_length=10)),
                ('observacoes_gerais', models.TextField(blank=True)),
                ('assinatura', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('assinado', 'Assinado')], default='pendente', max_length=10)),
                ('token_publico', models.CharField(blank=True, max_length=64, unique=True)),
                ('data_assinatura', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checklists', to='mecanica.cliente')),
                ('oficina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='accounts.oficina')),
                ('ordem', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='mecanica.ordemservico')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checklists', to='mecanica.veiculo')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='DanoChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('arranhao', 'Arranhão'), ('amassado', 'Amassado'), ('quebrado', 'Quebrado'), ('faltando', 'Faltando'), ('outro', 'Outro')], default='arranhao', max_length=20)),
                ('regiao', models.CharField(choices=[('frente', 'Frente'), ('traseira', 'Traseira'), ('lateral_esq', 'Lateral Esquerda'), ('lateral_dir', 'Lateral Direita'), ('teto', 'Teto'), ('interior', 'Interior'), ('motor', 'Motor')], max_length=20)),
                ('pos_x', models.FloatField(default=0.5)),
                ('pos_y', models.FloatField(default=0.5)),
                ('descricao', models.CharField(blank=True, max_length=300)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='checklists/')),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='danos', to='mecanica.checklistentrada')),
            ],
        ),
    ]
