# Generated by Django 6.0.5 on 2026-05-13 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mecanica', '0002_checklistentrada_danochecklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='token_publico',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
    ]
