# Generated by Django 6.0.5 on 2026-05-14 02:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('mecanica', '0003_ordemservico_token_publico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=20)),
                ('veiculo_placa', models.CharField(max_length=10)),
                ('veiculo_descricao', models.CharField(blank=True, max_length=200)),
                ('servico_desejado', models.CharField(max_length=300)),
                ('data_hora', models.DateTimeField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado'), ('concluido', 'Concluído')], default='pendente', max_length=15)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to='mecanica.cliente')),
                ('oficina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='accounts.oficina')),
                ('ordem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamento', to='mecanica.ordemservico')),
            ],
            options={
                'ordering': ['data_hora'],
            },
        ),
        migrations.CreateModel(
            name='AlertaEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_no_alerta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lido', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('peca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='mecanica.peca')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='GarantiaServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prazo_dias', models.IntegerField(default=90)),
                ('data_inicio', models.DateField(default=django.utils.timezone.now)),
                ('observacoes', models.TextField(blank=True)),
                ('servico_os', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='garantia', to='mecanica.servicoos')),
            ],
        ),
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('problema_relatado', models.TextField(blank=True)),
                ('observacoes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado'), ('expirado', 'Expirado')], default='pendente', max_length=15)),
                ('token_publico', models.CharField(blank=True, max_length=64, unique=True)),
                ('validade', models.DateField(blank=True, null=True)),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orcamentos', to='mecanica.cliente')),
                ('mecanico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orcamentos', to='mecanica.funcionario')),
                ('oficina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orcamentos', to='accounts.oficina')),
                ('ordem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orcamento_origem', to='mecanica.ordemservico')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orcamentos', to='mecanica.veiculo')),
            ],
            options={
                'ordering': ['-criado_em'],
                'unique_together': {('oficina', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='ItemOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('servico', 'Serviço'), ('peca', 'Peça')], default='servico', max_length=10)),
                ('descricao', models.CharField(max_length=300)),
                ('quantidade', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='mecanica.orcamento')),
            ],
        ),
        migrations.CreateModel(
            name='ComissaoMecanico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentual', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pago', models.BooleanField(default=False)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comissoes', to='mecanica.funcionario')),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comissoes', to='mecanica.ordemservico')),
            ],
            options={
                'ordering': ['-criado_em'],
                'unique_together': {('funcionario', 'ordem')},
            },
        ),
    ]
