# Generated by Django 6.0.5 on 2026-05-14 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mecanica', '0004_agendamento_alertaestoque_garantiaservico_orcamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='telefone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
