# Generated by Django 6.0.5 on 2026-05-14 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mecanica', '0005_alter_agendamento_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='percentual_comissao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
