# Generated by Django 6.0.5 on 2026-05-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mecanica', '0006_funcionario_percentual_comissao'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='quilometragem_saida',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
