# Generated by Django 6.0.5 on 2026-05-15 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_oficina_logo_cor_primaria'),
        ('mecanica', '0007_ordemservico_quilometragem_saida'),
    ]

    operations = [
        migrations.CreateModel(
            name='GarantiaDefault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prazo_dias', models.IntegerField(default=90)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('oficina', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='garantia_default', to='accounts.oficina')),
            ],
        ),
    ]
