# Generated by Django 6.0.5 on 2026-05-18 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mecanica', '0008_garantia_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='email_cliente',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
