# Generated by Django 6.0.5 on 2026-05-18 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mecanica', '0009_agendamento_email_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='status',
            field=models.CharField(choices=[('aberta', 'Aberta'), ('em_andamento', 'Em Andamento'), ('aguardando_peca', 'Aguardando Peça'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], db_index=True, default='aberta', max_length=20),
        ),
    ]
