# Generated by Django 6.0.5 on 2026-08-26 00:57
#
# ATENÇÃO: o índice de logauditoria já existe no banco, mas sob outro nome
# (herança de um index_together antigo). Um RenameIndex normal falha com
# 'relation "mecanica_lo_oficina_idx" does not exist'. Por isso esta migration
# NÃO executa DDL no banco — apenas sincroniza o STATE do Django com o modelo,
# eliminando o aviso "changes not yet reflected in a migration". O índice físico
# continua existindo e funcionando com o nome que já tem.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mecanica', '0015_diagnostico'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RenameIndex(
                    model_name='logauditoria',
                    new_name='mecanica_lo_oficina_250f15_idx',
                    old_name='mecanica_lo_oficina_idx',
                ),
            ],
            database_operations=[],  # nenhum DDL: o índice físico fica como está
        ),
    ]
