# Generated by Django 6.0.5 on 2026-08-26 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mecanica', '0015_diagnostico'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='logauditoria',
            new_name='mecanica_lo_oficina_250f15_idx',
            old_name='mecanica_lo_oficina_idx',
        ),
    ]
