# Generated by Django 6.0.5 on 2026-05-13 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(default='smtp.gmail.com', max_length=200)),
                ('port', models.IntegerField(default=587)),
                ('use_tls', models.BooleanField(default=True)),
                ('use_ssl', models.BooleanField(default=False)),
                ('username', models.CharField(blank=True, max_length=200)),
                ('password', models.CharField(blank=True, max_length=200)),
                ('from_email', models.EmailField(blank=True, max_length=254)),
                ('from_name', models.CharField(default='DoMecânico', max_length=100)),
                ('ativo', models.BooleanField(default=False)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração de E-mail',
            },
        ),
        migrations.CreateModel(
            name='NotificacaoAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('nova_oficina', 'Nova oficina cadastrada'), ('trial_expirando', 'Trial expirando'), ('pagamento', 'Evento de pagamento'), ('erro_sistema', 'Erro de sistema')], max_length=30)),
                ('titulo', models.CharField(max_length=200)),
                ('mensagem', models.TextField()),
                ('lida', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notificação Admin',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='TemplateEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('boas_vindas', 'Boas-vindas'), ('trial_expirando', 'Trial expirando'), ('assinatura_ativa', 'Assinatura ativada'), ('assinatura_cancelada', 'Assinatura cancelada'), ('pagamento_recusado', 'Pagamento recusado'), ('checklist_cliente', 'Checklist para cliente')], max_length=50, unique=True)),
                ('assunto', models.CharField(max_length=200)),
                ('corpo_html', models.TextField()),
                ('ativo', models.BooleanField(default=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Template de E-mail',
            },
        ),
        migrations.CreateModel(
            name='LogAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('info', 'Info'), ('aviso', 'Aviso'), ('erro', 'Erro'), ('critico', 'Crítico')], default='info', max_length=10)),
                ('categoria', models.CharField(choices=[('auth', 'Autenticação'), ('assinatura', 'Assinatura'), ('pagamento', 'Pagamento'), ('oficina', 'Oficina'), ('sistema', 'Sistema'), ('email', 'E-mail')], default='sistema', max_length=20)),
                ('mensagem', models.TextField()),
                ('detalhe', models.JSONField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Atividade',
                'ordering': ['-criado_em'],
            },
        ),
    ]
