# Generated by Django 6.0.5 on 2026-05-16 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_oficina_logo_cor_primaria'),
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GatewayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('stripe', 'Stripe'), ('asaas', 'Asaas'), ('pagseguro', 'PagSeguro'), ('manual', 'Manual (sem gateway)')], default='manual', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('chave_publica', models.CharField(blank=True, max_length=500)),
                ('chave_secreta', models.CharField(blank=True, max_length=500)),
                ('webhook_secret', models.CharField(blank=True, max_length=500)),
                ('ambiente', models.CharField(choices=[('sandbox', 'Sandbox'), ('producao', 'Produção')], default='sandbox', max_length=10)),
                ('config_extra', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração de Gateway',
            },
        ),
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=20, unique=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('paga', 'Paga'), ('vencida', 'Vencida'), ('cancelada', 'Cancelada')], default='pendente', max_length=20)),
                ('vencimento', models.DateField()),
                ('data_pagamento', models.DateTimeField(blank=True, null=True)),
                ('metodo_pagamento', models.CharField(blank=True, max_length=50)),
                ('gateway_id', models.CharField(blank=True, max_length=200)),
                ('gateway_provider', models.CharField(blank=True, max_length=20)),
                ('link_pagamento', models.URLField(blank=True, max_length=500)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('assinatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faturas', to='accounts.assinatura')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo', models.CharField(max_length=50)),
                ('gateway_id', models.CharField(blank=True, max_length=200)),
                ('gateway_provider', models.CharField(blank=True, max_length=20)),
                ('dados_gateway', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('fatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='adminpanel.fatura')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
