# Generated by Django 6.0.5 on 2026-05-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_gatewayconfig_fatura_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatewayconfig',
            name='provider',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('asaas', 'Asaas'), ('pagseguro', 'PagSeguro'), ('abacatepay', 'Abacate Pay'), ('manual', 'Manual (sem gateway)')], default='manual', max_length=20),
        ),
    ]
