# Generated by Django 6.0.5 on 2026-05-18 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_add_abacatepay_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fatura',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('paga', 'Paga'), ('vencida', 'Vencida'), ('cancelada', 'Cancelada')], db_index=True, default='pendente', max_length=20),
        ),
    ]
