# Generated by Django 6.0.5 on 2026-08-27 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0009_anuncio'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatewayconfig',
            name='pix_chave',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='gatewayconfig',
            name='pix_favorecido',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='gatewayconfig',
            name='pix_qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='pix/'),
        ),
        migrations.AddField(
            model_name='gatewayconfig',
            name='whatsapp_suporte',
            field=models.CharField(blank=True, help_text='Só dígitos com DDI, ex: 5511986815754', max_length=30),
        ),
    ]
