# Generated by Django 6.0.5 on 2026-05-13 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Oficina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('endereco', models.CharField(blank=True, max_length=300)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(blank=True, max_length=2)),
                ('cep', models.CharField(blank=True, max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(choices=[('starter', 'Starter'), ('pro', 'Pro')], max_length=20, unique=True)),
                ('nome', models.CharField(max_length=50)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
                ('max_usuarios', models.IntegerField()),
                ('max_clientes', models.IntegerField(help_text='-1 = ilimitado')),
                ('max_os_mes', models.IntegerField(help_text='-1 = ilimitado')),
                ('max_pecas', models.IntegerField(help_text='-1 = ilimitado')),
                ('tem_nota_fiscal', models.BooleanField(default=False)),
                ('tem_relatorios', models.BooleanField(default=False)),
                ('tem_fotos_veiculo', models.BooleanField(default=False)),
                ('descricao', models.TextField(blank=True)),
                ('destaque', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['preco'],
            },
        ),
        migrations.CreateModel(
            name='MembroOficina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(choices=[('admin', 'Administrador'), ('mecanico', 'Mecânico'), ('atendente', 'Atendente')], default='admin', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membro', to=settings.AUTH_USER_MODEL)),
                ('oficina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros', to='accounts.oficina')),
            ],
        ),
        migrations.CreateModel(
            name='Assinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('trial', 'Período de Teste'), ('ativa', 'Ativa'), ('cancelada', 'Cancelada'), ('suspensa', 'Suspensa')], default='trial', max_length=20)),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('trial_fim', models.DateTimeField(blank=True, null=True)),
                ('renovacao_automatica', models.BooleanField(default=True)),
                ('oficina', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assinatura', to='accounts.oficina')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.plano')),
            ],
        ),
        migrations.CreateModel(
            name='PagamentoSimulado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado')], default='aprovado', max_length=20)),
                ('metodo', models.CharField(default='cartao_simulado', max_length=50)),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('assinatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='accounts.assinatura')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
