# Generated by Django 6.0.5 on 2026-05-14 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=False)),
                ('evolution_url', models.URLField(blank=True, help_text='URL base da Evolution API ex: http://localhost:8080')),
                ('evolution_api_key', models.CharField(blank=True, max_length=200)),
                ('instance_name', models.CharField(blank=True, max_length=100)),
                ('instance_token', models.CharField(blank=True, max_length=200)),
                ('msg_os_concluida', models.BooleanField(default=True)),
                ('msg_orcamento_enviado', models.BooleanField(default=True)),
                ('msg_agendamento_confirmado', models.BooleanField(default=True)),
                ('template_os_concluida', models.TextField(blank=True, default='')),
                ('template_orcamento', models.TextField(blank=True, default='')),
                ('template_agendamento', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('oficina', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_config', to='accounts.oficina')),
            ],
        ),
        migrations.CreateModel(
            name='ConviteOficina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('papel', models.CharField(choices=[('admin', 'Administrador'), ('mecanico', 'Mecânico'), ('atendente', 'Atendente')], default='atendente', max_length=20)),
                ('token', models.CharField(default='', max_length=64, unique=True)),
                ('aceito', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='convites_enviados', to=settings.AUTH_USER_MODEL)),
                ('oficina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convites', to='accounts.oficina')),
            ],
        ),
    ]
