# Generated by Django 6.0.5 on 2026-05-14 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_configuracaowhatsapp_conviteoficina'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissaoMembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulos', models.JSONField(default=list)),
                ('membro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permissoes', to='accounts.membrooficina')),
            ],
        ),
    ]
