# Generated by Django 6.0.5 on 2026-05-14 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_permissaomembro'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='modulos_disponiveis',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
