# Generated by Django 6.0.5 on 2026-05-18 11:20

from django.db import migrations, models
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    Oficina = apps.get_model('accounts', 'Oficina')
    used = set()
    for oficina in Oficina.objects.all():
        base = slugify(oficina.nome) or f'oficina-{oficina.pk}'
        slug = base
        n = 1
        while slug in used:
            slug = f'{base}-{n}'
            n += 1
        used.add(slug)
        oficina.slug_publico = slug
        oficina.save(update_fields=['slug_publico'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_oficina_logo_cor_primaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='oficina',
            name='descricao_publica',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='oficina',
            name='horario_funcionamento',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='oficina',
            name='perfil_publico_ativo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='oficina',
            name='servicos_oferecidos',
            field=models.TextField(blank=True, help_text='Um serviço por linha'),
        ),
        # Add slug WITHOUT unique constraint first
        migrations.AddField(
            model_name='oficina',
            name='slug_publico',
            field=models.SlugField(blank=True, max_length=100, default=''),
            preserve_default=False,
        ),
        # Populate slugs for existing rows
        migrations.RunPython(populate_slugs, migrations.RunPython.noop),
        # Now add the unique constraint
        migrations.AlterField(
            model_name='oficina',
            name='slug_publico',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
