# Generated by Django 6.0.5 on 2026-05-18 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_oficina_descricao_publica_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assinatura',
            name='status',
            field=models.CharField(choices=[('trial', 'Período de Teste'), ('ativa', 'Ativa'), ('cancelada', 'Cancelada'), ('suspensa', 'Suspensa')], db_index=True, default='trial', max_length=20),
        ),
        migrations.AlterField(
            model_name='pagamentosimulado',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado')], db_index=True, default='aprovado', max_length=20),
        ),
    ]
