# Generated by Django 6.0.5 on 2026-08-26 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_plano_add_diagnosticos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oficina',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True),
        ),
    ]
